# Generated by Django 4.2 on 2023-04-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='posted',
            new_name='created',
        ),
    ]
